"""Create column updated_at

Revision ID: f7ed779ac636
Revises: 5a9cb26e92ff
Create Date: 2024-09-07 20:15:06.717978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ed779ac636'
down_revision: Union[str, None] = '5a9cb26e92ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'updated_at')
    # ### end Alembic commands ###
